ALTER USER  FOTA IDENTIFIED BY oracle; 
/ 
GRANT SELECT ON FOTA.MEAS_NUMERICLIMIT TO EREPORTS; 
/ 
CREATE SYNONYM EREPORTS.FOTA_MEAS_NUMERICLIMIT FOR FOTA.MEAS_NUMERICLIMIT; 
/ 
GRANT SELECT ON FOTA.STEP_MSGPOPUP TO EREPORTS; 
/ 
CREATE SYNONYM EREPORTS.FOTA_STEP_MSGPOPUP FOR FOTA.STEP_MSGPOPUP; 
/ 
GRANT SELECT ON FOTA.STEP_PASSFAIL TO EREPORTS; 
/ 
CREATE SYNONYM EREPORTS.FOTA_STEP_PASSFAIL FOR FOTA.STEP_PASSFAIL; 
/ 
GRANT SELECT ON FOTA.STEP_RESULT TO EREPORTS; 
/ 
CREATE SYNONYM EREPORTS.FOTA_STEP_RESULT FOR FOTA.STEP_RESULT; 
/ 
GRANT SELECT ON FOTA.STEP_STRINGVALUE TO EREPORTS; 
/ 
CREATE SYNONYM EREPORTS.FOTA_STEP_STRINGVALUE FOR FOTA.STEP_STRINGVALUE; 
/ 
GRANT SELECT ON FOTA.UUT_RESULT TO EREPORTS; 
/ 
CREATE SYNONYM EREPORTS.FOTA_UUT_RESULT FOR FOTA.UUT_RESULT; 
/ 
exit; 
/ 
